### ISSUE TITLE
Cant find a way to install or make it work

### ISSUE THREAD

**Issue by MattPerSua** [kwilkins/roll20-stats-extension#20]
Hello, wanted to see the stats of my campaign but im having trouble installing the extension.

Firefox tell me that the file is corrupt and chrome finds the manifest but when installed show me an error
![screenshot_671](https://github.com/kwilkins/roll20-stats-extension/assets/95320115/30de8014-3c4c-4d9e-b540-2aee76bfee1b)

**Comment by marchetti554** [comment]
Hey, sadly the **README** is not clear for people without development knowledge, try installing **nodeJS** and running `npm install & npm run build`, there will be a new folder called `dist` with the `index.html` inside, use that folder when adding the extension to the browser :) just did that and it worked.

**Comment by kwilkins** [comment]
Hi @marchetti554 I've added a link to the extension page on the chrome store. You should be able to install directly from there. Hope that helps if you are still experiencing any issues!

Apologies for it missing and being MIA, our family has recently doubled and I haven't had time to return to this pet project until now :)
